### ISSUE TITLE
Node shutdowns itself after "Detected difference between set of nodes received from the discovery service" message

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akka.Cluster.Discovery#16]
Consul log
```
2018/01/23 20:30:35 [WARN] agent: Check "service:test@node1:2552/" missed TTL, is now critical
2018/01/23 20:30:35 [INFO] agent: Synced check "service:test@node1:2552/"
2018/01/23 20:30:35 [INFO] agent: Synced check "service:test@node1:2552/"
2018/01/23 20:30:45 [WARN] agent: Check "service:test@node1:2552/" missed TTL, is now critical
2018/01/23 20:30:45 [INFO] agent: Synced check "service:test@node1:2552/"
2018/01/23 20:31:49 [INFO] agent: Deregistered service "test@node1:2552/"
2018/01/23 20:31:49 [INFO] agent: Check "service:test@node1:2552/" for service "test@node1:2552/" has been critical for too long; deregistered service
2018/01/23 20:31:49 [INFO] agent: Deregistered check "service:test@node1:2552/"
```
The node log
```
23.01.2018 20:30:35.572 INFO  [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,   24] - Detected difference between set of nodes received from the discovery service [] and the one provided by the cluster [akka.tcp://test@node1:2552] 
23.01.2018 20:30:35.572 INFO  [Akka.Cluster.ClusterCoreDaemon,   10] - Marking node [akka.tcp://test@node1:2552] as [Down] 
23.01.2018 20:30:36.112 INFO  [Akka.Cluster.ClusterCoreDaemon,   24] - Shutting down myself 
23.01.2018 20:30:36.112 INFO  [Akka.Event.DummyClassForStringSources,   10] - Cluster Node [akka.tcp://test@node1:2552] - Shutting down... 
23.01.2018 20:30:36.112 INFO  [Akka.Event.DummyClassForStringSources,    9] - Cluster Node [akka.tcp://test@node1:2552] - Successfully shut down 
23.01.2018 20:30:36.196 INFO  [Akka.Remote.RemoteActorRefProvider+RemotingTerminator,   28] - Shutting down remote daemon. 
23.01.2018 20:30:36.201 INFO  [Akka.Remote.RemoteActorRefProvider+RemotingTerminator,   10] - Remote daemon shut down; proceeding with flushing remote transports. 
23.01.2018 20:30:36.283 INFO  [Akka.Event.DummyClassForStringSources,   28] - Remoting shut down 
23.01.2018 20:30:36.283 INFO  [Akka.Remote.RemoteActorRefProvider+RemotingTerminator,   10] - Remoting shut down. 
```
The node and the Consul agent were running on the same machine, so the times are synchronized.

**Comment by Horusiath** [comment]
When using this plugin, information about the cluster state can be obtained from 2 sources:

1. Akka cluster membership state itself
2. Consult list of registered services

I've decided that in the case of conflict, we let the consul to be an arbitrary source of truth (but also a single point of failure). That seem to make sense from point of view of this plugin - we need consul's perspective to obtain seed nodes, and we additionally get a referee in case of network partitions.

Here it looks like service has been deregistered from consul (due to unfulfilled TTL check), but since it was single node cluster, it decided to also shutdown itself.

Less than hour ago I've pushed new NuGet release - it should cover of missed TTL checks (TTLs are twice as long as pinging message interval) + few other improvements. See: #15

**Comment by vasily-kirichenko** [comment]
> Here it looks like service has been deregistered from consul (due to unfulfilled TTL check), but since it was single node cluster, it decided to also shutdown itself.

Look carefully at the times. The sequence was as following:

1. The node received empty list:

> 23.01.2018 20:30:35.572 INFO  [Akka.Cluster.Discovery.Consul.ConsulDiscoveryService,   24] - Detected difference between set of nodes received from the discovery service [] and the one provided by the cluster [akka.tcp://test@node1:2552] 

2. Consul missed TTL and deregisters the service:

> 2018/01/23 20:31:49 [INFO] agent: Deregistered service "test@node1:2552/"
2018/01/23 20:31:49 [INFO] agent: Check "service:test@node1:2552/" for service "test@node1:2552/" has been critical for too long; deregistered service
2018/01/23 20:31:49 [INFO] agent: Deregistered check "service:test@node1:2552/"

**Comment by vasily-kirichenko** [comment]
Maybe logging sending Alive messages with debug level could help to investigate it further? I mean, to be sure that the node sends Alive, then receives empty node list and shutdown itself.

**Comment by Horusiath** [comment]
When taking nodes for comparison, we only [ask for healthy ones](https://github.com/Horusiath/Akka.Cluster.Discovery/blob/2b84abfca1750ad14d62e4320f447bd4c76e4773/src/Akka.Cluster.Discovery.Consul/ConsulDiscoveryService.cs#L55). This is why we got empty list - missed TTL caused consul to mark node as unhealthy, so it won't appear on cluster state reconciliation. Therefore later it shutdowns itself and around minute after Consul deregistered it (as designed).

The problem here is that for reconciliation of state between akka.net cluster and consul [we take only nodes marked as healthy](https://github.com/Horusiath/Akka.Cluster.Discovery/blob/master/src/Akka.Cluster.Discovery/DiscoveryService.cs#L215), while periodic health problems are worrying but not critical. I'll fix this soon.

**Comment by vasily-kirichenko** [comment]
I see. Could we add an independent config setting to specify the period with which Alive message should be sent? On heavy load there may be no free threads for long time, so I'd prefer setting like TTL = 1m, AliveInterval = 5s.

**Comment by Horusiath** [comment]
We could make it configurable, but it shouldn't be too long - 1m is a time suitable for deregistration, not marking node as unhealthy. With TTL=1m, a node could be dead for 30s and still be used as potential seed node (as consul sees it as healthy due to long TTL) by other nodes trying to join the cluster.

**Comment by vasily-kirichenko** [comment]
OK, I've deployed the node with 0.1.0 and set 

alive-interval = 30s
alive-timeout = 2m

will see if it helps.

**Comment by vasily-kirichenko** [comment]
The two node cluster has survived over night, everything is OK, I'm closing this.
